### ISSUE TITLE
hello , I think have a bug , 

### ISSUE THREAD

**Issue by lairdnote** [qur/gopy#6]
### my system: ubuntu 12.04 lts desktop

root@lairdnote-Parallels:/home/lairdnote/Go/src/Hello# gccgo -v
Using built-in specs.
COLLECT_GCC=gccgo
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.7/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.2-0ubuntu3' --with-bugurl=file:///usr/share/doc/gccgo-4.7/README.Bugs --enable-languages=c,c++,go --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --enable-targets=all --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.7.2 (Ubuntu/Linaro 4.7.2-0ubuntu3)
### I use this example,

http://gopy.qur.me/extensions/examples.html
### test.py

import simple

simple.example("Hell", {12:True})

simple.so file is create ,
but i use python shell  and test.py  is have bug ,

root@lairdnote-Parallels:/home/lairdnote/Go/src/Hello# python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import simple
ImportError: /usr/lib/gccgo/libgopy.ext.so: undefined symbol: libgo_math.math..import

**Comment by qur** [comment]
What version of gopy are you using?

The latest version in the ext branch on github should work, but I 
haven't had time to produce a new source tarball or .deb package yet.

## 

Julian

**Comment by lairdnote** [comment]
thanks for you
