### ISSUE TITLE
Install on Mac OS X

### ISSUE THREAD

**Issue by dhermes** [qur/gopy#7]
I started an SVN checkout of `gccgo` on my Mac and after 30 minutes I gave up on waiting. Is there a more sane way of installing? As of right now, I would say the friction is too great to get real use, but this project could be massively useful in speeding up code!

**Comment by qur** [comment]
The new Python 3.11 branch doesn't need gccgo, so it should be easier to get going. Not sure that it's going to make anything faster though.
